name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Composer Validate'
                        run: composer validate --ansi

                    -
                        name: 'PHPStan'
                        run: composer phpstan --ansi

                    -
                        name: 'Coding Standard'
                        run: composer fix-cs --ansi

                    -
                        name: 'Tests'
                        run: vendor/bin/phpunit

                    -
                        name: "Run easy levels"
                        run:
                            # first run updates internal config to import early
                            vendor/bin/phpstan analyse --configuration phpstan-easylevel-50.neon
                            # second run applies the rules
                            vendor/bin/phpstan analyse --configuration phpstan-easylevel-50.neon

                            # same as above, testing level change
                            vendor/bin/phpstan analyse --configuration phpstan-easylevel-100.neon
                            vendor/bin/phpstan analyse --configuration phpstan-easylevel-100.neon



        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
